# GitHub Action 的名稱
name: Deploy to GitHub Pages

# 觸發條件：當推送到 main 分支時自動執行
on:
  push:
    branches:
      - main # 您可以更改為您的主要分支名稱，例如 master

# 工作流程執行的內容
jobs:
  build-and-deploy:
    # 運行的環境
    runs-on: ubuntu-latest

    # 執行的步驟
    steps:
      # 步驟一：複製您的儲存庫程式碼到虛擬環境中
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      # 步驟二：部署到 GitHub Pages
      # 這是一個社群開發的 Action，專門用來處理靜態網頁部署
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # 指定要部署到的分支，通常命名為 gh-pages
          folder: . # 指定要部署的資料夾，因為我們是單一 index.html 在根目錄，所以是 "."
